export const ROUTING_MANAGER = {
  ROOT: '/',
  EMPLOYEE_PAGE: '/employeePage',
  EMPLOYEE_PAGE_SEARCH: '/employeePage/search',
  SIGN_IN: '/signin/',
  SIGN_IN_PASSWORD: '/signin/:changedPassword',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token/',
  ALL_PRODUCTS: '/products',
  PRODUCT: '/products/:slug',
  CART: '/cart',
  ORDER_DETAILS: 'orderDetails',
  SINGLE_ORDER: 'orderSummary/:id',
  CHECKOUT: '/checkout',
  USER_PROFILE: '/user/:id',
  PAYMENT: '/payment',
  CONFIRM_ORDER: '/placeOrder',
  ORDER: '/order/:id',
  ORDER_HISTORY: '/orderHistory'
};
